
/*
 * Copyright (c) 2016 Dell Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License. You may obtain
 * a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT
 * LIMITATION ANY IMPLIED WARRANTIES OR CONDITIONS OF TITLE, FITNESS
 * FOR A PARTICULAR PURPOSE, MERCHANTABLITY OR NON-INFRINGEMENT.
 *
 * See the Apache Version 2.0 License for specific language governing
 * permissions and limitations under the License.
 */


/*
 * filename: db_api_linux_init.h
 */

/*
 * db_api_linux_inti.h
 */

#ifndef DB_API_LINUX_INTI_H_
#define DB_API_LINUX_INTI_H_

#include "std_error_codes.h"
#ifdef __cplusplus
extern "C" {
#endif

/**
 * Initialize the linux DB API with the db
 * @return standard return code
 */
t_std_error cps_api_linux_init(void);

/**
 * Clear the existing DS API event count that is generated when a new netlink message
 * is process and translated to a DS event.
 */
void cps_api_event_count_clear(void);

/**
 * Get number of DS API events generated by the linux API. Each DS event increases the
 * counter by 1.
 * @return a uint64_t containing the number of events that were counted since last reset
 *     NOTE: Debug only.. can wrap
 */
uint64_t cps_api_event_count_get(void);

#ifdef __cplusplus
}
#endif

#endif /* DB_API_LINUX_INTI_H_ */
